### ISSUE TITLE
"Matching" the histograms

### ISSUE THREAD

**Issue by Annanilsson-code** [Annanilsson-code/ProjectAppliedMolBiophys#14]
https://github.com/Annanilsson-code/ProjectAppliedMolBiophys/blob/c9064f17b185e7167b2f266a6c531fbd0febc174/cc_calculation_prot.py#L29

When multiplying with 10, this is what we get. Does it matter if the noise histogram doesn't match the experimental histogram in height/value on y axis? I guess that the data might differ anyway in how many "matches" we get per bin?

![image](https://user-images.githubusercontent.com/74772895/100875022-b708fd80-34a5-11eb-988a-b9f1634a1df0.png)

**Comment by FilipeMaia** [comment]
That looks reasonable. How do the images look visually?

**Comment by Annanilsson-code** [comment]
The images look like this: 
![image](https://user-images.githubusercontent.com/74772895/100895435-d875e380-34bd-11eb-9586-98665ed334f0.png)
![image](https://user-images.githubusercontent.com/74772895/100895455-dd3a9780-34bd-11eb-8d09-7b29a7f061d4.png)
![image](https://user-images.githubusercontent.com/74772895/100895469-e297e200-34bd-11eb-94db-0a7eaec7b436.png)

**Comment by Annanilsson-code** [comment]
Tomorrow we could discuss particledata.py, because that code is more complete than cc_calculation_prot.py in this folder.
