### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by FilipeMaia** [Annanilsson-code/ProjectAppliedMolBiophys#5]
You should not put code issues in the code itself https://github.com/Annanilsson-code/ProjectAppliedMolBiophys/blob/24acdaeb7b47ae283740bfa9c873dfa15b503af0/cc_calculation.py#L42-L53
Also that line makes the file invalid in terms of syntax.
Better to open an issue about it instead.

**Comment by Annanilsson-code** [comment]
Okay!

**Comment by FilipeMaia** [comment]
Fixed by 3740fe5.
