### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by Annanilsson-code** [Annanilsson-code/ProjectAppliedMolBiophys#6]
https://github.com/Annanilsson-code/ProjectAppliedMolBiophys/blob/3740fe51845d61ba04cd757b608e49d4c2201327/cc_calculation.py#L79

Sometimes the infile seems to be written in a wrong way, so that the MDS algorithm cannot interpret it.

**Comment by FilipeMaia** [comment]
Try using a fixed random seed, e.g.:

```python
import numpy as np
np.random.seed(0)
...
```

**Comment by Annanilsson-code** [comment]
Unfortunately it doesn't help... But after I run the code a couple of times, it produces a correct infile so I guess that's ok even if it takes some time

**Comment by FilipeMaia** [comment]
Be aware that all files produced will now be exactly identical.

**Comment by Annanilsson-code** [comment]
Ok, but how can they be identical?

**Comment by FilipeMaia** [comment]
I mean repeated runs of the script will produce exactly the same output, not that the multiple images within a run will be the same.

**Comment by Annanilsson-code** [comment]
Ok, I see
