### ISSUE TITLE
This line gives an error when run on the cluster

### ISSUE THREAD

**Issue by Annanilsson-code** [Annanilsson-code/ProjectAppliedMolBiophys#7]
https://github.com/Annanilsson-code/ProjectAppliedMolBiophys/blob/3994d8dc44090c03cc20fdaaee91308e3ced94a0/cc_calculation.py#L81

This happens when running cc_calculation on the cluster (but not on our own computers).

-bash-4.1$ python cc_calculation.py
  File "cc_calculation.py", line 79
    print(i+1,'\t', j+1, '\t', cc_matrix[i,j], file=f)
                                                   ^
SyntaxError: invalid syntax

**Comment by FilipeMaia** [comment]
This is caused by different print syntax in Python 2.
