### ISSUE TITLE
Changing the noise

### ISSUE THREAD

**Issue by Annanilsson-code** [Annanilsson-code/ProjectAppliedMolBiophys#9]
https://github.com/Annanilsson-code/ProjectAppliedMolBiophys/blob/086a59e4f5c62a7f8399ea3dce546ae990c80786/cc_calculation.py#L60

Is it correct to write like this when varying the noise in the images?

noise_ellipse[i] = numpy.random.poisson(image1*number)

**Comment by FilipeMaia** [comment]
yes
